/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface UeSideDrawer {
    'changeTitle': (title: string) => void;
    'open': () => void;
    'opened': boolean;
    'title': string;
  }
  interface UeSideDrawerAttributes extends StencilHTMLAttributes {
    'opened'?: boolean;
    'title'?: string;
  }

  interface UeStockPrice {
    'stockSymbol': string;
  }
  interface UeStockPriceAttributes extends StencilHTMLAttributes {
    'stockSymbol'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'UeSideDrawer': Components.UeSideDrawer;
    'UeStockPrice': Components.UeStockPrice;
  }

  interface StencilIntrinsicElements {
    'ue-side-drawer': Components.UeSideDrawerAttributes;
    'ue-stock-price': Components.UeStockPriceAttributes;
  }


  interface HTMLUeSideDrawerElement extends Components.UeSideDrawer, HTMLStencilElement {}
  var HTMLUeSideDrawerElement: {
    prototype: HTMLUeSideDrawerElement;
    new (): HTMLUeSideDrawerElement;
  };

  interface HTMLUeStockPriceElement extends Components.UeStockPrice, HTMLStencilElement {}
  var HTMLUeStockPriceElement: {
    prototype: HTMLUeStockPriceElement;
    new (): HTMLUeStockPriceElement;
  };

  interface HTMLElementTagNameMap {
    'ue-side-drawer': HTMLUeSideDrawerElement
    'ue-stock-price': HTMLUeStockPriceElement
  }

  interface ElementTagNameMap {
    'ue-side-drawer': HTMLUeSideDrawerElement;
    'ue-stock-price': HTMLUeStockPriceElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
