/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface UeSideDrawer {
    'title': string;
  }
  interface UeSideDrawerAttributes extends StencilHTMLAttributes {
    'title'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'UeSideDrawer': Components.UeSideDrawer;
  }

  interface StencilIntrinsicElements {
    'ue-side-drawer': Components.UeSideDrawerAttributes;
  }


  interface HTMLUeSideDrawerElement extends Components.UeSideDrawer, HTMLStencilElement {}
  var HTMLUeSideDrawerElement: {
    prototype: HTMLUeSideDrawerElement;
    new (): HTMLUeSideDrawerElement;
  };

  interface HTMLElementTagNameMap {
    'ue-side-drawer': HTMLUeSideDrawerElement
  }

  interface ElementTagNameMap {
    'ue-side-drawer': HTMLUeSideDrawerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
